apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: santa-deployment
spec:
  selector:
    matchLabels:
      app: santa
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: santa
    spec:
      containers:
        - name: santa
          image: adijaiswal/santa:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: santa-svc
spec:
  selector:
    app: santa
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service.

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: santa-ingress
  labels:
    name: santa
spec:
  rules:
  - host: privy-challenge.my.id
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: santa-svc
            port: 
              number: 8080
