apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - image: us-docker.pkg.dev/cloudrun/container/secretsanta
          ports:
            - name: http1
              containerPort: 8080